# Generated by Django 2.1 on 2018-09-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rouboapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respage01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('detail_url', models.URLField(max_length=500)),
                ('rate', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
